-- migrate:up
CREATE TABLE users (
    id INT NOT NULL AUTO_INCREMENT,
    email VARCHAR(200) NOT NULL UNIQUE KEY,
    password VARCHAR(200) NOT NULL,
    name VARCHAR(50) NOT NULL,
    address VARCHAR(1000) NOT NULL,
    point INT NOT NULL CHECK( point >= 0 ) DEFAULT 100000,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);
-- migrate:down
DROP TABLE users